---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: kubeapps-issuer-production
  namespace: kubeapps
spec:
  acme:
    email: dvsquash@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: kubeapps-issuer-production-letsencrypt
    http01: {}
