---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: '20'
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: kubeapps-issuer-production
  name: kubeapps-ingress
  namespace: kubeapps
spec:
  rules:
  - host: kubeapps.askharilabs.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: kubeapps
          servicePort: 80
  tls:
  - hosts:
    - kubeapps.askharilabs.tech
    secretName: kubeapps-ingress-cert
