---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: do-cluster-administrators
subjects:
- kind: ServiceAccount
  name: {{ k8s_username }}
  namespace: {{ k8s_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
