---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: do-{{ k8s_namespace }}-administrators
  namespace: {{ k8s_namespace }}
subjects:
- kind: ServiceAccount
  name: {{ k8s_username }}
  namespace: {{ k8s_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
