apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  creationTimestamp: 2019-02-17T19:55:58Z
  name: workflow-controller-configmap
  namespace: argo
  resourceVersion: "1736979"
  selfLink: /api/v1/namespaces/argo/configmaps/workflow-controller-configmap
  uid: 0b8efc55-32ee-11e9-83c3-8638b3e0d312
data:
  config: |
    artifactRepository:
      s3:
        bucket: argo
        endpoint: minio-storage.minio.svc.cluster.local:9000
        insecure: true
        # accessKeySecret and secretKeySecret are secret selectors.
        # It references the k8s secret named 'argo-artifacts'
        # which was created during the minio helm install. The keys,
        # 'accesskey' and 'secretkey', inside that secret are where the
        # actual minio credentials are stored.
        accessKeySecret:
          name: argo-artifacts
          key: argokey
        secretKeySecret:
          name: argo-artifacts
          key: argosecret
