---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: default
spec:
  storageClassName: storageos-users-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
